#include "Level2.h"
void Level2::init(Player* mPlayer)
{
	player = mPlayer;
	levelFinished = false;
	sREntrance.init(0);
	lREntranceToLobby.init(1);
	bRLobby.init(0);
	lRLobbyToDresser1.init(1);
	lRLobbyToDresser2.init(1);
	Dresser.init(2);
	lRLobbyToObservatory.init(1);
	mRObservatory.init(0);
	lRNorthLabEntrance.init(1);
	lRWestLabEntrance.init(1);
	mRLab.init(2);
	lRWestLibraryEntrance.init(1);
	mRLibary.init(2);
	lREastLibraryEntrance.init(1);
	sRStable.init(2);
	lRObservatoryToStable.init(1);
	lRObservatoryToBoss1.init(1);
	lRObservatoryToBoss2.init(1);
	mRBossRoom.init(3);

	sREntrance.roomName = "sREntrance";
	lREntranceToLobby.roomName = "lREntranceToLobby";
	bRLobby.roomName = "bRLobby";
	lRLobbyToDresser1.roomName = "lRLobbyToDresser1";
	lRLobbyToDresser2.roomName = "lRLobbyToDresser2";
	Dresser.roomName = "Dresser";
	lRLobbyToObservatory.roomName = "lRLobbyToObservatory";
	mRObservatory.roomName = "mRObservatory";
	lRNorthLabEntrance.roomName = "lRNorthLabEntrance";
	lRWestLabEntrance.roomName = "lRWestLabEntrance";
	mRLab.roomName = "mRLab";
	lRWestLibraryEntrance.roomName = "lRWestLibraryEntrance";
	mRLibary.roomName = "mRLibary";
	lREastLibraryEntrance.roomName = "lREastLibraryEntrance";
	sRStable.roomName = "sRStable";
	lRObservatoryToStable.roomName = "lRObservatoryToStable";
	lRObservatoryToBoss1.roomName = "lRObservatoryToBoss1";
	lRObservatoryToBoss2.roomName = "lRObservatoryToBoss2";
	mRBossRoom.roomName = "mRBossRoom";
	
	levelRooms.push_back(&sREntrance);
	levelRooms.back()->createPortal(2, "lREntranceToLobby", 3, levelRooms.back()->sizeY);
	levelRooms.push_back(&lREntranceToLobby);
	levelRooms.back()->createPortal(1, "sREntrance", 2, 0);
	levelRooms.back()->createPortal(2, "bRLobby", 2, levelRooms.back()->sizeY);
	levelRooms.push_back(&bRLobby);
	levelRooms.back()->createPortal(1, "lREntranceToLobby", 8, 0);
	levelRooms.back()->createPortal(2, "lRLobbyToDresser1", 8, levelRooms.back()->sizeY);
	levelRooms.back()->createPortal(3, "lRLobbyToObservatory", levelRooms.back()->sizeX, 3);
	levelRooms.push_back(&lRLobbyToDresser1);
	levelRooms.back()->createPortal(1, "bRLobby", 2, 0);
	levelRooms.back()->createPortal(2, "lRLobbyToDresser2", 2, levelRooms.back()->sizeY);
	levelRooms.back()->createPortal(3, "lRWestLabEntrance", levelRooms.back()->sizeX, 6);
	levelRooms.push_back(&lRLobbyToDresser2);
	levelRooms.back()->createPortal(1, "lRLobbyToDresser1", 2, 0);
	levelRooms.back()->createPortal(2, "Dresser", 2, levelRooms.back()->sizeY);
	levelRooms.back()->createPortal(3, "lRWestLibraryEntrance", levelRooms.back()->sizeX, 6);
	levelRooms.push_back(&Dresser);
	levelRooms.back()->createPortal(1, "lRLobbyToDresser2", 3, 0);
	levelRooms.push_back(&lRLobbyToObservatory);
	levelRooms.back()->createPortal(4, "bRLobby", 0, 2);
	levelRooms.back()->createPortal(3, "mRObservatory", levelRooms.back()->sizeX, 2);
	levelRooms.back()->createPortal(2, "lRNorthLabEntrance", 12, levelRooms.back()->sizeY);
	levelRooms.push_back(&mRObservatory);
	levelRooms.back()->createPortal(1, "lRObservatoryToStable", 5, 0);
	levelRooms.back()->createPortal(4, "lRLobbyToObservatory", 0, 3);
	levelRooms.back()->createPortal(2, "lRObservatoryToBoss1", 5, levelRooms.back()->sizeY);
	levelRooms.push_back(&lRNorthLabEntrance);
	levelRooms.back()->createPortal(1, "lRLobbyToObservatory", 2, 0);
	levelRooms.back()->createPortal(2, "mRLab", 2, levelRooms.back()->sizeY);
	levelRooms.push_back(&lRWestLabEntrance);
	levelRooms.back()->createPortal(4, "lRLobbyToDresser1", 0, 2);
	levelRooms.back()->createPortal(3, "mRLab", levelRooms.back()->sizeX, 2);
	levelRooms.push_back(&mRLab);
	levelRooms.back()->createPortal(1, "lRNorthLabEntrance", 5, 0);
	levelRooms.back()->createPortal(4, "lRWestLabEntrance", 0, 3);
	levelRooms.push_back(&lRWestLibraryEntrance);
	levelRooms.back()->createPortal(4, "lRLobbyToDresser2", 0, 2);
	levelRooms.back()->createPortal(3, "mRLibary", levelRooms.back()->sizeX, 2);
	levelRooms.push_back(&mRLibary);
	levelRooms.back()->createPortal(4, "lRWestLibraryEntrance", 0, 3);
	levelRooms.back()->createPortal(3, "lREastLibraryEntrance", levelRooms.back()->sizeX, 3);
	levelRooms.push_back(&lREastLibraryEntrance);
	levelRooms.back()->createPortal(4, "mRLibary", 0, 2);
	levelRooms.back()->createPortal(3, "lRObservatoryToBoss2", levelRooms.back()->sizeX, 2);
	levelRooms.push_back(&sRStable);
	levelRooms.back()->createPortal(2, "lRObservatoryToStable", 3, levelRooms.back()->sizeY);
	levelRooms.push_back(&lRObservatoryToStable);
	levelRooms.back()->createPortal(1, "sRStable", 2, 0);
	levelRooms.back()->createPortal(2, "mRObservatory", 2, levelRooms.back()->sizeY);
	levelRooms.push_back(&lRObservatoryToBoss1);
	levelRooms.back()->createPortal(1, "mRObservatory", 2, 0);
	levelRooms.back()->createPortal(2, "lRObservatoryToBoss2", 2, levelRooms.back()->sizeY);
	levelRooms.push_back(&lRObservatoryToBoss2);
	levelRooms.back()->createPortal(1, "lRObservatoryToBoss1", 2, 0);
	levelRooms.back()->createPortal(2, "mRBossRoom", 2, levelRooms.back()->sizeY);
	levelRooms.back()->createPortal(4, "lREastLibraryEntrance", 0, 6);
	levelRooms.push_back(&mRBossRoom);
	levelRooms.back()->createPortal(1, "lRObservatoryToBoss2", 5, 0);
	currentRoom = levelRooms.front();
	setItemsInRooms(2);
}